### ISSUE TITLE
Support for filtering of child classes

### ISSUE THREAD

**Issue by zackattackz** [fschick/FilterExpressionCreator#3]
I'd like to propose a feature to support filtering for specific instances of child classes in a hierarchy.

Suppose we have the following classes:
```cs
public class Fooer {
  public string Foo { get; set; }
}

public class Barrer : Fooer {
  public string Bar { get; set; }
}

public class Bazzer : Fooer {
  public string Baz { get; set; }
}
```

If we are filtering against a collection of `Fooer`s, then it would be useful to be able to specify a filter for only `Barrer`s or only `Bazzer`s. (or some detailed combination of filters for properties in `Barrer` and `Bazzer`

An example of the syntax for such a filter could be:

```cs
var barFilter = new EntityFilter<Barrer>();
var fooFilter = new EntityFilter<Fooer>().AddSubclassFilter(barFilter);
```

This would filter a collection of `Fooer`s to only include instances of `Barrer`s

Or, as another example, say we want all `Barrer`s, and all `Bazzer`s that have Baz == "test":

```cs
var barFilter = new EntityFilter<Barrer>();
var bazFilter = new EntityFilter<Bazzer>().Add(b => b.Baz, "=test");
var fooFilter = new EntityFilter<Fooer>().AddSubclassFilter(barFilter).AddSubclassFilter(bazFilter);
```

I've started work for this feature in [this branch](https://github.com/zackattackz/FilterExpressionCreator/tree/SubclassFilters) please view if you get a chance and let me know your thoughts.

There's quite a bit to consider here, for instance: How would these filters be serialized?

Thank you for reading.

**Comment by fschick** [comment]
### Intention
Can you give me more information about the idea behind the subclass filter?

Why wouldn't it make sense to create concrete filters using `new EntityFilter<Bazzer>` and `new EntityFilter<Barrer>()` instead of using a common one which will be separated again later?

You can cast filters between classes by simple property name matching
```csharp
var bazzerFilter = new EntityFilter<Bazzer>().Add(...);
var fooerFilter = bazzerFilter.Cast<Fooer>();
```
Or, if more complex logic is required, you can utilize [AutoMapper.Extensions.ExpressionMapping](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping)

### Your changes
To be serializable, the only way I see is to switch `SubclassFilter.SubclassType` to string and match the subclass by name. I use the same compromise for `NestedFilter.PropertyName`

Did you already evaluate the behavior of the Expression created via  `var instanceIsSubclassLambda = ...` in [EntityFilter.cs](https://github.com/zackattackz/FilterExpressionCreator/blob/03c97abdc9624c959225eeba503de62f34f6d679/FS.FilterExpressionCreator/Filters/EntityFilter.cs#L511) against Entity Framework Core?

**Comment by zackattackz** [comment]
Just wanted to say thank you for your time, and thank you especially for making this project open source :)

So to answer your questions:

> Can you give me more information about the idea behind the subclass filter?

To explain a little more, I think the best use case for these filters would be in a listing page of entities, similar to what is showcased in your demo for this project.

However this would be different, we would want to list all the entities in a type hierarchy, and apply all varieties of filters across all the different sub types.

The listing page would maybe only show the common properties in the super class (Id, Name, Type, etc...), but a user could get more detailed information once they have that entity's Id and Type.

I've created a [demo project](https://github.com/zackattackz/RazorPagesEFCoreFilterDemo) that references my fork, you could try out the variety of filters and see what queries EF core generates. (in the console)

The goal after all is to try to make the most efficient EF queries possible.

EF core does support [entity type hierarchy mappings](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#entity-type-hierarchy-mapping) to a table-per-hierarchy model. So this type conversion is translated as a SQL predicate along the lines of "WHERE [a].[Type] = N'TypeName'" (assuming [Type] is the discriminator column name and TypeName is a sub class type name)

> Why wouldn't it make sense to create concrete filters using `new EntityFilter<Bazzer>` and `new EntityFilter<Barrer>()` instead of using a common one which will be separated again later?

Well from my understanding, I believe this could work if you are only filtering against one subtype, but if you want to create more complex filters with many subtypes then it's not possible (I think)

> You can cast filters between classes by simple property name matching

Also unsure if this would work if the goal is to filter many sub types. (please correct me if I'm wrong)

> Or, if more complex logic is required, you can utilize [AutoMapper.Extensions.ExpressionMapping](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping)

I'm unfamiliar with this library but if you think this could do the same type of filtering as my demo please let me know :)

I hope the demo proves to be helpful in understanding what I'm trying to implement. Thanks again and if you need any clarifications please let me know.

**Comment by zackattackz** [comment]
[This file in particular](https://github.com/zackattackz/RazorPagesEFCoreFilterDemo/blob/bdd806b757357b92680b83dedb00a9c2aad36c4d/RazorPagesEFCoreFilterDemo/Pages/Animals/List.cshtml.cs) in the demo is worth reading to see the usage of the sub class filters

**Comment by zackattackz** [comment]
On further inspection it seems that using Cast will not work, because if you do

```cs
var bazzerFilter = new EntityFilter<Bazzer>().Add(x => x.Baz ...);
var fooerFilter = bazzerFilter.Cast<Fooer>();
```
The fooerFilter will be empty, and not retain the information from the bazzerFilter. (the PropertyFilter will be removed in [this line](https://github.com/fschick/FilterExpressionCreator/blob/6bda8c63be6da8a7e461dd7befadeb6039061dea/FS.FilterExpressionCreator/Filters/EntityFilter.cs#L187))

I don't believe this could trivially be done with Cast, without changing code there.

**Comment by fschick** [comment]
I reviewed the demo and understand your requirement but need a bit time to investigate for possible solutions.

**Comment by zackattackz** [comment]
Cool. I put together my fork solution pretty quickly to just get something to work. So I'm not sure that it is the best solution. Looking forward to your thoughts.

**Comment by fschick** [comment]
I have thought about several solutions
* Get the feature "out of the box"
Maybe, by adding a property `IncludeDerivedTypes` to `FilterEntityAttribute`. Afterwards all classes within the app domain would have be scanned. Discarded, too complex and not consistent how nested filters are handled.
* Add a new project `FS.FilterExpressionCreator.Extensions` and handle the feature as 'standalone'. Benefits: Separation of concerns, existing code does not become more complex. Drawback: I do not see it is possible to integrate it directly with `EntityFilter`. I might be done as extension method for `EntityFilter.Compile().Add(...)`.
* Integrate it into `EntityFilter` as suggested. This seems currently the best solution for me.

Please let me know if you prefer another or not listed solution than the third one.

To get the suggested solution final, the following should be solved:
* Naming: I'm not a native English speaker. But for me 'DereivedClass' sounds more clear than 'Subclass'. Therefore `DerivedClassFilter`. Are you a native speaker?
* `AddSubclassFilter` should be `Add` to be consistent with nested filters. Or adding of nested filter should be `AddNestedFilter` (breaking change)
* `SubclassFilter` must be (JSON) serializable. The only way I see is to change `SubclassType` to string and recover it during `CreateFilter` via reflection. Must be well-tested, especially with generic classes (e.g. `Mammal<Canine>`)
*  Is the paremeter `isInclusive` of `AddSubclassFilter` required? This would break with the current logic 'no OR filters between properties'. How much does your use case depends on this feature?
* Try to prevent `Expression.Invoke` in [EntityFilter](https://github.com/zackattackz/FilterExpressionCreator/blob/03c97abdc9624c959225eeba503de62f34f6d679/FS.FilterExpressionCreator/Filters/EntityFilter.cs#L509). `Expression.Invoke` and `Expression.Call` made some problems with custom registered database functions in Entity Framework in the past. As an alternative, writing complete unit and integration tests is also a valid solution.
* Write unit tests. Current functionality is 100% tested (as far as it could be). Missing code coverage comes from unreachable, non-excludable code.

Who makes the changes? I am glad to accept pull requests, but would also be willing to do it by myself. Because my limited free time it could take a while. Nevertheless I always able to discuss or help with technical details.

**Comment by zackattackz** [comment]
Hm I would have to agree that the third solution seems like the way to go when compared to the other two. Unless you didn't want to complicate the existing code base much more, then the second solution may be better.

As for the other problems, I'll offer my opinions in order:
- I am a native speaker, your English is great! It seems that Microsoft refers to such a relationship as "[base class and derived class](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/inheritance#background-what-is-inheritance)". So, moving forward it is probably best to refer to them as such. I will add a commit to change the terminology.
- This is true, I wasn't sure here what you would prefer so I just went with a new method. But I'll defer this final decision to you.
-  As for serialization: I think what you suggest is a good idea. I don't believe there should be some problem with conflicting names of types? That would just be a user error. Generic classes seem tricky though, I will have to think more about that (Are they supported by EF Core?).
- `isInclusive` was my way of answering the question "How could you add filters for one specific derived type, while also not filtering out the other types in the hierarchy?". I suppose it isn't necessary, but I wanted to include an answer to that question. I definitely need to add more unit testing for it though, not sure if it works as I intended 100%. Could you expand on what you mean in "This would break with the current logic 'no OR filters between properties'."? I just am unsure where the current logic is exactly.
- As for preventing `Expression.Invoke`: The only way I can think of to avoid calling it in the spot you linked would be to create an [ExpressionVisitor](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-modify-expression-trees) and replace any instances of `x` with `Convert(x, DerivedType)`. Not sure if that would work, but it would avoid `Invoke`. But it would also add some complexity. If `Invoke` is fully supported by EF Core in this context then maybe we could just use it as is?
- Yes I will be sure to write some more extensive tests. For now I just wanted to try to get something working to demonstrate what I meant. But going forward I'll be sure to write more.

I'd be happy to work on the feature more and submit pull requests for code review. :)

I want to note that I am not critically requiring this feature in any business setting. I had a similar idea to make an open source project like FilterExpressionCreator, and found that you already did everything I was going to do 😅. So I'd like to contribute to your project and the open source community by making this feature (while also sharpening my c sharp skills). Maybe it could help someone in need down the line.

That said, I don't want you to worry too much about this if your time is better spent elsewhere.

So I will begin by writing more tests. Then I'll try to get serialization working. If I have any questions while I work would you like me to post them in this issue?

Thanks!

**Comment by fschick** [comment]
Great, thank you for contributing!

* Naming: I have changed my mind. `AddDerivedClassFilter(...)` is more related to clean code. I will add methods with new names for nested filtering and mark the old ones as obsolete. Are you able to rebase your work on git to prevent a merge commit? Otherwise I do the change after the feature is complete.
* Serialization: Keep it simple, stupid (KISS). For me, it's perfectly sufficient if a unique and meaningful exception is thrown for derived classes having generic arguments. An issue or pull request can be opened at any time if someone needs such functionality. When you use the full qualified name of the class it should be enough. Naming conflicts should be very rarely and always a design error in the users code.
* `Expression.Invoke`: An `ExpressionVisitor` is already implemented, see [ReplaceParameter](https://github.com/fschick/FilterExpressionCreator/blob/6bda8c63be6da8a7e461dd7befadeb6039061dea/FS.FilterExpressionCreator.Abstractions/Extensions/ExpressionExtensions.cs#L79). Within this method I used `Invoke` earlier which failed at least with EF Core 3.x.

If you have any questions that may be relevant to the public, please post them here in the issue. For other questions feel free to contact me via my e-mail. The address can be found in my [public profile](https://github.com/fschick/).

**Comment by fschick** [comment]
Parameter `isInclusive`: Currently there is no way to filter for two or more properties with logical `OR`. I made this design decision because I didn't see a way to map such logic in a user-friendly way in the URL parameter or Swagger UI ([documentation is missing](https://github.com/fschick/FilterExpressionCreator/issues/4)). Currently URL filter is done by 

```scss
// Years of experience > 2
/api/v1/Freelancer/GetFreelancers?yearsOfExperience=>2 

// Years of experience > 2 OR NULL
/api/v1/Freelancer/GetFreelancers?yearsOfExperience=>2,ISNULL

// Years of experience > 2 AND Years of experience <= 5
/api/v1/Freelancer/GetFreelancers?yearsOfExperience=>2&yearsOfExperience=<=5 
```
I strive to offer the complete feature set where possible for all input variants. However, it is not a blocker if it is not reasonably possible everywhere.

**Comment by zackattackz** [comment]
Awesome.

I could rebase if you'd like to make that naming change.

Ok though for everything else :) and to be compatible with the property filters I've removed `isInclusive`.

Also, another question:

Do you think it would be user error to have something like this:
```cs
var barFilter = new EntityFilter<Barrer>()
    .Add(b => b.Foo, "=TestOne");
var fooFilter = new EntityFilter<Fooer>()
    .Add(f => f.Foo, "=TestTwo")
    .AddDerivedClassFilter(barFilter);
```

It wouldn't really make sense to have a filter on a derived class that is conflicting with a filter on the base class.

I suppose to handle this case, we could check in `AddDerivedClassFilter` and `Add` to see if adding said filter would cause a conflict.

Could loop through `PropertyFilters` and `NestedFilters` on each Add to see if a conflict would arise.

However it would make sense to have something like this:
```cs
var barFilter = new EntityFilter<Barrer>()
    .Add(b => b.Foo, "=TestOne");
var bazFilter = new EntityFilter<Bazzer>()
    .Add(b => b.Foo, "=TestTwo");
var fooFilter = new EntityFilter<Fooer>()
    .AddDerivedClassFilter(barFilter)
    .AddDerivedClassFilter(bazFilter);
```

Because this is essentially saying "Only keep barrers and bazzers. If it is a barer, only keep it if Foo == TestOne. If it is a bazzer, only keep it if Foo == TestTwo.".

I will make some test cases for these edge cases, but before I start implementing more I just wanted to get your opinion.

EDIT: See below comment for second thoughts on this.

**Comment by zackattackz** [comment]
Well thinking about it more...

Doing
```cs
var barFilter = new EntityFilter<Barrer>()
    .Add(b => b.Foo, "=TestOne");
var fooFilter = new EntityFilter<Fooer>()
    .Add(f => f.Foo, "=TestTwo")
    .AddDerivedClassFilter(barFilter);
```

Could have the meaning "If the instance is of type Barrer, then check if Foo == "TestOne". But if the instance is of type Fooer, then check if Foo == "TestTwo".

So then should a base filter have a TypeIs expression added to the front like: `(if Type is BaseClass AndAlso ...rest of base class filters...) OrElse ...derived class filters...` ?

Or should the filters on the base class HAVE TO apply to ALL derived classes.

(essentially what I already have implemented, with `..base class filters... AndAlso ...derived class filters...`)

Is my confusion here understandable?

I see two options here:
- Treat all filters on the base class as required, throwing an exception if a conflict arises.
- Treat all filters on the base class as only specifically for instances of the base class. Filters for the same property on derived class instances must be (re)defined in the derived class filter

I think option 2 is the better way to go

**Comment by zackattackz** [comment]
And taking this thought process one step further...

Would we be better off scraping `AddDerivedClassFilter` altogether in favor of implementing this feature in a similar fashion to `EntityFilterSet`?

Where the user would define something like this:

```cs
public class FooerHierarchyFilter : EntityHierarchyFilter<Fooer>
{
    public EntityFilter<Fooer> Fooer { get; set; }
    public EntityFilter<Barrer> Barrer { get; set; }
    public EntityFilter<Bazzer> Bazzer { get; set; }
}
```

Then it could be used by just setting the corresponding filters as needed like:

```cs
var fooerFilter = new FooerHierarchyFilter();
fooerFilter.Fooer = new EntityFilter<Fooer>()
    .Add(x => x.Foo, "=TestTwo");
fooerFilter.Barrer = new EntityFilter<Barrer>()
    .Add(x => x.Foo "=TestOne");
```

this would be equivalent in function to what I was saying above in:
```cs
var barFilter = new EntityFilter<Barrer>()
    .Add(b => b.Foo, "=TestOne");
var fooFilter = new EntityFilter<Fooer>()
    .Add(f => f.Foo, "=TestTwo")
    .AddDerivedClassFilter(barFilter);
```

The `EntityHierarchyFilter<Fooer>` class could have a `CreateFilter` method of its own that would compile the final `Expression<Func<Fooer, bool>>`

I like this approach because we could actually keep the `EntityFilter` code completely untouched, while still providing this functionality (I believe).

**Comment by zackattackz** [comment]
> I see two options here:
>
> * Treat all filters on the base class as required, throwing an exception if a conflict arises.
> * Treat all filters on the base class as only specifically for instances of the base class. Filters for the same property on derived class instances must be (re)defined in the derived class filter

The first option seems to lend itself to the original `AddDerivedClassFilter` way of doing things, and the second option seems to work better with the `EntityHierarchyFilter` way.

Ahhh, so much to think about here 😭

I will wait to hear back before I continue. Will keep thinking about it though.

**Comment by fschick** [comment]
I agree, the case is more complex than first thought.

**Concept to combine filters:**
Would it be fine to combine filters for the _same_ property, regardless of it's occurrence in the hierarchy? In the mind of "delegate properties of base class to it"

`giraffeFilter.Add(g => g.Age > 1)`, `elephantFilter.Add(e => e.Age < 2)` becomes the same as
`animalFilter.Add(g => g.Age > 1).Add(g => g.Age < 2)` which combines both expressions with AND.

This would also reflect the current behavior without derived classes. And it prevents to re-think about "should it be possible combine two properties with OR".

I try to switch to a user's point of view: Is `Giraffe.Age` not the same as `Animal.Age`? If you like to go to the zoo and use it's homepage to see what animals you can expect, do you really like to search for `Giraffe.Age > 1` OR `Elephant.Age < 2` with one query? Or is the user more interested to see young animals between 1 and 2 years old? `Animal.Age > 1` AND `Animal.Age < 2`?

What do you think?

**About `isInclusive` or not `isInclusive`**:
What will be returned when two properties of derived classes are filtered? When common properties are delegated to base class (as suggested above) the derived filters could work separately.
```csharp
class Animal { public int Age { get; set; } }
class Giraffe: Animal { public int NeckLength { get; set; } }
class Elephant: Animal { public int TrunkLength { get; set; } }

var giraffeFilter = new EntityFilter<Giraffe>()
    .AddFilter(a => a.Age, ">5")
    .Add(g => g.NeckLength, ">2");

var elephantFilter = new EntityFilter<Elephant>()
    .Add(e => e.TrunkLength, ">1");

var animalFilter = new EntityFilter<Animal>()
    .AddDerivedClassFilter(giraffeFilter)
    .AddDerivedClassFilter(elephantFilter)

// Results in:
a => a.Age > 5 && ( (a is Giraffe && a.NeckLength > 2) || (a is Elephant && a.TrunkLength > 1) )
```

Would this work?

**EntityHierarchyFilter:**
I'd like to prevent it for the first step. I feel like it would be more a patch instead of removing the cause: My "not so good" design desiccation to mix the model `EntityFilter`and the application logic. This design causes problems in a current businesses-case too.

**Some technical hints:**
Handling of filtered properties against MVC / Swagger UI: It's impossible to use same property name twice. Therefore you would be forced to rename in the case below. Otherwise a runtime exception it thrown. This should not hit your changes directly, only for your understanding.
```csharp
class Animal
{
     [Filter(Name = "Age")]
    public virtual int Age { get; set; }
}

class Canine : Animal
{
    [Filter(Name = "CanineAge")]
    override public int Age { get; set; }
}
```

`Type is BaseClass` as you proposed above is always true in C# and can be omitted
```csharp
class Animal { }
class Canine : Animal { }

(new Canine() is Animal) == true
(new Animal() is Animal) == true
```

Keyword `new` for properties: I've always ignored the use case which creates a new field on `Canine` with the same name as `Age` in `Animal`. I don't like to think about such bad code and have just ignored the case so far. I would keep it that way for now.
```csharp
class Animal
{
    public int Age { get; set; }
}

class Canine : Animal
{
    new public int Age { get; set; }
}
```

**Proposal: Separation of tasks**

* First step is to get the derived filter working. With a solid code base and as near as possible to the existing logic.
* Afterwards it's possible to think about Separation of Concerns (SoC) for the `EntityFilter` and business logic. Perhaps I need to do it in parallel to your work because it hit's a current businesses-case of one of my customers.
* If there is still time, it makes sense to think about "OR" filters between properties.
* And last but not least, the library [Sieve](https://github.com/Biarity/Sieve/) linked above, is catching my interest in offering something along the lines of sorting and paging.

**Comment by fschick** [comment]
Closed due inactivity.
